spring.application.name=checkpoint-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/checkpoint_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Kx9mP2vL8qR4tY7wZ1aB3cD6eF0gH5jK9nM2pQ4sT7v 
jwt.expiration=86400000
